version: 2.1

orbs:
  platform-helpers-general: okta/general-platform-helpers@1.9.4

parameters:
  preview:
    type: string
    default: ""
  preview_with_redirect:
    type: string
    default: ""

commands:
  install-deps:
    steps:
      - restore_cache:
          name: Restore Yarn dependency cache
          keys:
            - v6-yarn-deps-{{ checksum "yarn.lock" }}
            # allow for partial cache hits
            - v6-yarn-deps-
      - run:
          name: Install dependencies with Yarn
          command: yarn install --frozen-lockfile --ignore-platform
      - save_cache:
          name: Save Yarn dependency cache
          key: v6-yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
            - packages/@okta/vuepress-plugin-active-header-links/node_modules/
            - packages/@okta/vuepress-site/node_modules/
            - ~/.cache/

jobs:
  netlify_manual:
    docker:
      - image: cimg/node:14.21.3-browsers
    resource_class: xlarge
    steps:
      - run:
          name: Has secrets?
          command: |
            NETLIFY_AUTH_TOKEN="$NETLIFY_AUTH_TOKEN_2"
            NETLIFY_SITE_ID="$NETLIFY_SITE_ID_2"
            if [ -z "$NETLIFY_AUTH_TOKEN" ] || [ -z "$NETLIFY_SITE_ID" ]; then
              echo "Missing required secrets."
              exit 1
            fi
      - checkout
      - install-deps
      - run:
          name: Build preview
          command: |
            # mkdir -p packages/@okta/vuepress-site/dist
            # pushd packages/@okta/vuepress-site/dist
            # echo hi>readme.md
            # popd
            yarn build
      - persist_to_workspace:
          root: packages/@okta/vuepress-site/dist
          paths:
            - .

  netlify_publish:
    docker:
      - image: cimg/node:18.20.0-browsers
    resource_class: xlarge
    steps:
      - attach_workspace:
          at: packages/@okta/vuepress-site/dist
      - run:
          command: |
            npm install --save-dev netlify-cli@24.0.1
            npx netlify deploy --no-build --alias=preview-${CIRCLE_PULL_REQUEST##*/} --filter @okta/vuepress-site

workflows:
  wf_netlify_manual:
    when: << pipeline.parameters.preview >>
    jobs:
      - netlify_manual
      - netlify_publish:
          requires:
            - netlify_manual

