version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    version_requirement_updates: "auto"
  - package_manager: "javascript"
    directory: "/pakcages/@okta/vuepress-site"
    update_schedule: "weekly"
    version_requirement_updates: "auto"
  - package_manager: "javascript"
    directory: "/pakcages/@okta/vuepress-plugin-active-header-links"
    update_schedule: "weekly"
    version_requirement_updates: "auto"
  - package_manager: "javascript"
    directory: "/pakcages/@okta/vuepress-plugin-qualtrics-feedback"
    update_schedule: "weekly"
    version_requirement_updates: "auto"
  - package_manager: "javascript"
    directory: "/pakcages/@okta/vuepress-theme-prose"
    update_schedule: "weekly"
    version_requirement_updates: "auto"
  - package_manager: "javascript"
    directory: "/pakcages/@okta/vuepress-theme-default"
    update_schedule: "weekly"
    version_requirement_updates: "auto"
