# Generates the guides-list.json file
# that is used to ensure all the dynamic guides paths work
# in server-side rendering

echo '{
  "_note": "This file is auto-generated by build-guides-list script.  Do not modify this file directly",
  "guides": [ ';
echo "$(
  find ./guides -type f \
    | sed -E \
    -e 's_^\.__' `# remove prefix` \
    -e 's_/guides/([^/]*/)([^/*]*/)([^/*]*/)[^\.]*\.md_/guides/\1\3\2_' `# switch path, drop filename` \
    -e 's_index\.md__' `# drop index.md` \
    -e '\_^/([^/]*/){1,3}$_ d' `# drop partial paths (anything without framework)`\
    | sort \
    | uniq `# drop duplicates (from multiple snippets in a section)` \
    | sed -e 's_.*_{ "path": "&", "content": " " },_' `# convert to json` \
    -e '$ s_,$__' `# remove trailing comma on last line`
)"
echo '] }'

